import 'asset_tags.dart';
import 'brush.dart';
import 'brush_extension_defaults.dart';

/// Approved extension presets. BrushService appends these to its built-ins.
List<Brush> brushExtensionPresets() => const <Brush>[
      Brush(
        id: 'Brush0022',
        name: 'ネット',
        size: 20,
        opacity: 100,
        spacing: 100,
        stabilization: true,
        stabilizationStrength: 35,
        pixelMode: false,
        pressureOn: BrushPressureOnSettings(
          size: PressureRangeSetting(enabled: false, weak: 100, strong: 100),
          opacity: PressureRangeSetting(enabled: false, weak: 100, strong: 100),
          blur: PressureRangeSetting(enabled: false, weak: 0, strong: 0),
          edgeJitter: PressureRangeSetting(enabled: false, weak: 0, strong: 0),
          mixing: PressureMixingOnSetting(enabled: false, mode: BrushMixingMode.simple, weakRate: 0, strongRate: 0),
        ),
        fadeMode: FadeMode.off,
        strokeDecay: false,
        rotation: true,
        density: 1,
        scatter: 0,
        lateralRepeatEnabled: true,
        lateralRepeatCount: 4,
        lateralRepeatSpacing: BrushExtensionDefaults.lateralRepeatSpacing,
        tipShape: BrushTipShape.hollowSquare,
        tags: <String>[AssetTagKeys.decoration, AssetTagKeys.background],
      ),
      Brush(
        id: 'Brush0023',
        name: '髪の毛',
        size: 28,
        opacity: 100,
        spacing: 1,
        stabilization: true,
        stabilizationStrength: 45,
        pixelMode: false,
        pressureOn: BrushPressureOnSettings(
          size: PressureRangeSetting(enabled: true, weak: 20, strong: 100),
          opacity: PressureRangeSetting(enabled: false, weak: 100, strong: 100),
          blur: PressureRangeSetting(enabled: false, weak: 0, strong: 0),
          edgeJitter: PressureRangeSetting(enabled: false, weak: 0, strong: 0),
          mixing: PressureMixingOnSetting(enabled: false, mode: BrushMixingMode.simple, weakRate: 0, strongRate: 0),
        ),
        fadeMode: FadeMode.weak,
        strokeDecay: false,
        rotation: false,
        density: 1,
        scatter: 0,
        outlineEnabled: true,
        outlineWidth: BrushExtensionDefaults.outlineWidth,
        outlineColor: BrushExtensionDefaults.outlineColor,
        foldEnabled: true,
        foldTriggerAngle: BrushExtensionDefaults.foldTriggerAngle,
        foldCurveStartRatio: BrushExtensionDefaults.foldCurveStartRatio,
        foldCurveStrength: BrushExtensionDefaults.foldCurveStrength,
        foldLengthRatio: BrushExtensionDefaults.foldLengthRatio,
        foldEndTaperRatio: BrushExtensionDefaults.foldEndTaperRatio,
        foldWaveEnabled: true,
        foldWaveEndRatio: BrushExtensionDefaults.hairFoldWaveEndRatio,
        foldWaveTriggerAngle: BrushExtensionDefaults.foldWaveTriggerAngle,
        tags: <String>[AssetTagKeys.clothing],
      ),
      Brush(
        id: 'Brush0024',
        name: '前髪',
        size: 32,
        opacity: 100,
        spacing: 1,
        stabilization: true,
        stabilizationStrength: 40,
        pixelMode: false,
        pressureOn: BrushPressureOnSettings(
          size: PressureRangeSetting(enabled: true, weak: 25, strong: 100),
          opacity: PressureRangeSetting(enabled: false, weak: 100, strong: 100),
          blur: PressureRangeSetting(enabled: false, weak: 0, strong: 0),
          edgeJitter: PressureRangeSetting(enabled: false, weak: 0, strong: 0),
          mixing: PressureMixingOnSetting(enabled: false, mode: BrushMixingMode.simple, weakRate: 0, strongRate: 0),
        ),
        fadeMode: FadeMode.weak,
        strokeDecay: false,
        rotation: false,
        density: 1,
        scatter: 0,
        customImagePaths: <String>[
          'assets/brushes/bangs_01.png',
          'assets/brushes/bangs_02.png',
          'assets/brushes/bangs_03.png',
          'assets/brushes/bangs_04.png',
          'assets/brushes/bangs_05.png',
        ],
        customImageSelectionMode: BrushImageSelectionMode.random,
        outlineEnabled: true,
        outlineWidth: BrushExtensionDefaults.outlineWidth,
        outlineColor: BrushExtensionDefaults.outlineColor,
        foldEnabled: true,
        foldTriggerAngle: BrushExtensionDefaults.foldTriggerAngle,
        foldCurveStartRatio: BrushExtensionDefaults.foldCurveStartRatio,
        foldCurveStrength: BrushExtensionDefaults.foldCurveStrength,
        foldLengthRatio: BrushExtensionDefaults.foldLengthRatio,
        foldEndTaperRatio: BrushExtensionDefaults.foldEndTaperRatio,
        foldWaveEnabled: false,
        foldWaveEndRatio: BrushExtensionDefaults.foldWaveEndRatio,
        foldWaveTriggerAngle: BrushExtensionDefaults.foldWaveTriggerAngle,
        tags: <String>[AssetTagKeys.clothing],
      ),
    ];
